services:
  # db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ssd
  #     MYSQL_DATABASE: ssd
  #   command: mysqld
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres:
    image: postgres:15-alpine
    container_name: postgres-ssd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ssd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ssd
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    ports:
      - "3000:3000"
    command: sh -c "npx prisma db push && npx prisma db seed && npm run dev"

  angular:
    build:
      context: ./frontend/ssd-angular
      dockerfile: Dockerfile
    container_name: ssd-angular
    depends_on:
      - api
    ports:
      - "4200:4200"


volumes:
  db_data:
  postgres_data: